services:
  windows:
    image: dockurr/windows:4.35
    container_name: windows
    environment:
      VERSION: "11"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - /ingot-data/docker/volumes/windows:/storage
    restart: always
    stop_grace_period: 2m
