version: "3"
services:
  # 服务名
  kafka-console-ui:
    # 容器名
    container_name: "kafka-console-ui"
    restart: always
    # 端口
    ports:
      - "7766:7766"
    # 持久化
    # volumes:
    # - ./data:/app/data
    # - ./log:/app/log
    # 防止读写文件有问题
    privileged: true
    user: root
    # 镜像地址
    image: "wdkang/kafka-console-ui"
    networks:
      - ingot-net
    expose:
      - "7766"

networks:
  ingot-net:
    external: true