version: "3.8"
services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: docker-registry.ingotcloud.top/nacos/nacos-server:${NACOS_VERSION}
    networks:
      - extnet
    volumes:
      - ${NACOS_VOLUME_ROOT}/nacos1:/home/nacos/logs
    ports:
      - "8181:8080"
      - "8848:8848"
      - "9848:9848"
    env_file:
      - ./env/cluster.env
    restart: always

  nacos2:
    hostname: nacos2
    container_name: nacos2
    image: docker-registry.ingotcloud.top/nacos/nacos-server:${NACOS_VERSION}
    networks:
      - extnet
    volumes:
      - ${NACOS_VOLUME_ROOT}/nacos2:/home/nacos/logs
    ports:
      - "8182:8080"
      - "8849:8848"
      - "9849:9848"
    env_file:
      - ./env/cluster.env
    restart: always

  nacos3:
    hostname: nacos3
    container_name: nacos3
    image: docker-registry.ingotcloud.top/nacos/nacos-server:${NACOS_VERSION}
    networks:
      - extnet
    volumes:
      - ${NACOS_VOLUME_ROOT}/nacos3:/home/nacos/logs
    ports:
      - "8183:8080"
      - "8850:8848"
      - "9850:9848"
    env_file:
      - ./env/cluster.env
    restart: always

networks:
  extnet:
    name: ingot-net
    external: true
