version: '3'
services:
  tracker:
    image: docker-registry.ingotcloud.top/ingot/fastdfs:0.1.0
    command: tracker
    networks:
      - extnet
    volumes:
      - /ingot-data/docker/volumes/fastdfs/tracker/conf:/etc/fdfs
      - /ingot-data/docker/volumes/fastdfs/tracker/data:/home/dfs
    ports:
      - "22122:22122"
    environment:
      - TRACKER_SERVER=tracker:22122
      - VIRTUAL_HOST=dfs-tracker.ingotcloud.top
      - VIRTUAL_PORT=22122
      - LETSENCRYPT_HOST=dfs-tracker.ingotcloud.top

  storage:
    depends_on:
      - tracker
    image: docker-registry.ingotcloud.top/ingot/fastdfs:0.1.0
    command: storage
    networks:
      - extnet
    volumes:
      - /ingot-data/docker/volumes/fastdfs/storage/conf:/etc/fdfs
      - /ingot-data/docker/volumes/fastdfs/storage/data:/home/dfs
      - /ingot-data/docker/volumes/fastdfs/storage/nginx:/usr/local/nginx/conf.d
    ports:
      - "23000:23000"
      - "8888:8888"
    environment:
      - TRACKER_SERVER=tracker:22122
      - VIRTUAL_HOST=dfs.ingotcloud.top
      - VIRTUAL_PORT=8888
      - LETSENCRYPT_HOST=dfs.ingotcloud.top

networks:
  extnet:
    name: ingot-net
    external: true